"""Cross-language compatibility check: this fixture was produced by the
real Node.js algorithm (same steps as src/lib/encryption/broker-keys.ts —
aes-256-gcm, IV||nothing separate, ciphertext = encrypted||authTag hex),
not reverse-engineered from the Python side. If this test passes, the
Python decrypt() is byte-for-byte compatible with what the Next.js app
actually writes to broker_connections.
"""

import pytest
from cryptography.exceptions import InvalidTag

from app.encryption import decrypt

FIXTURE_KEY_HEX = "a" * 64
FIXTURE_PLAINTEXT = "test-api-key-12345"
FIXTURE_CIPHERTEXT_HEX = "9b42359fc7aca9ad0ebd017a70db1062a63046f92a09537b447088c50df631889f62"
FIXTURE_IV_HEX = "dcef0fb7fa26ca7c992d5809cb1586ba"


def test_decrypt_matches_node_generated_fixture(monkeypatch):
    monkeypatch.setenv("ENCRYPTION_KEY", FIXTURE_KEY_HEX)
    from app.config import Settings

    monkeypatch.setattr("app.encryption.settings", Settings())

    result = decrypt(FIXTURE_CIPHERTEXT_HEX, FIXTURE_IV_HEX)
    assert result == FIXTURE_PLAINTEXT


def test_decrypt_raises_on_tampered_ciphertext(monkeypatch):
    monkeypatch.setenv("ENCRYPTION_KEY", FIXTURE_KEY_HEX)
    from app.config import Settings

    monkeypatch.setattr("app.encryption.settings", Settings())

    tampered = "0" + FIXTURE_CIPHERTEXT_HEX[1:]
    with pytest.raises(InvalidTag):
        decrypt(tampered, FIXTURE_IV_HEX)


# ----------------------------------------------------------------------------
# Two-field cross-language proof, generated after the encryption_iv
# reconciliation (supabase/migrations/
# 20260717000001_reconcile_remaining_tables_with_live.sql split
# broker_connections' single shared encryption_iv into api_key_iv /
# api_secret_iv). The fixture above only proves one ciphertext/iv pair
# round-trips — it doesn't prove two DIFFERENT fields encrypted under the
# same key with two DIFFERENT ivs both decrypt correctly, or that an iv
# genuinely belongs to its own ciphertext rather than being interchangeable.
# Both pairs below were generated by the real Node encrypt() algorithm in
# one run (same key, two separate calls — exactly how
# src/app/api/brokers/route.ts encrypts api_key and api_secret today).
# ----------------------------------------------------------------------------

TWO_FIELD_KEY_HEX = "a" * 64
API_KEY_PLAINTEXT = "test-api-key-field-value"
API_KEY_CIPHERTEXT_HEX = "072d7f6a1ab32a8d125db68b28c4e0c3b46d68a16278931e48ec43a51d1c705bc84c11eec201fbd4"
API_KEY_IV_HEX = "1ef7d3a236cb6fde863f9049b93e01cf"
API_SECRET_PLAINTEXT = "test-api-secret-field-value"
API_SECRET_CIPHERTEXT_HEX = "498166f4aeb4c1fdcbf8886ae8f7ba32a8c33bdf30d9793347168459888e7779e956cc1492bf7516538a80"
API_SECRET_IV_HEX = "1156beeefdb64671fd20c903549cf10a"


def test_decrypt_both_fields_independently_with_their_own_iv(monkeypatch):
    monkeypatch.setenv("ENCRYPTION_KEY", TWO_FIELD_KEY_HEX)
    from app.config import Settings

    monkeypatch.setattr("app.encryption.settings", Settings())

    assert decrypt(API_KEY_CIPHERTEXT_HEX, API_KEY_IV_HEX) == API_KEY_PLAINTEXT
    assert decrypt(API_SECRET_CIPHERTEXT_HEX, API_SECRET_IV_HEX) == API_SECRET_PLAINTEXT


def test_decrypt_rejects_a_ciphertext_paired_with_the_other_fields_iv(monkeypatch):
    """The actual point of splitting encryption_iv into two columns: an
    api_key ciphertext decrypted with api_secret's iv (or vice versa) must
    fail loudly, not silently return plausible-looking garbage. If this
    ever passed, the per-field IV columns would be security theater."""
    monkeypatch.setenv("ENCRYPTION_KEY", TWO_FIELD_KEY_HEX)
    from app.config import Settings

    monkeypatch.setattr("app.encryption.settings", Settings())

    with pytest.raises(InvalidTag):
        decrypt(API_KEY_CIPHERTEXT_HEX, API_SECRET_IV_HEX)
    with pytest.raises(InvalidTag):
        decrypt(API_SECRET_CIPHERTEXT_HEX, API_KEY_IV_HEX)
